-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 13:07:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vacaciones_recreativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vacaciones_recreativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vacaciones_recreativa` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `vacaciones_recreativa` ;

-- -----------------------------------------------------
-- Table `vacaciones_recreativa`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones_recreativa`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `vacaciones_recreativa`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `vacaciones_recreativa`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones_recreativa`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `vacaciones_recreativa`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreusu` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `identificacion` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `tipousuario_id` INT NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipousuario_idx` (`tipousuario_id` ASC),
  CONSTRAINT `fk_usuarios_tipousuario`
    FOREIGN KEY (`tipousuario_id`)
    REFERENCES `vacaciones_recreativa`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `vacaciones_recreativa`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones_recreativa`.`articulos` ;

CREATE TABLE IF NOT EXISTS `vacaciones_recreativa`.`articulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `vacaciones_recreativa`.`cupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones_recreativa`.`cupos` ;

CREATE TABLE IF NOT EXISTS `vacaciones_recreativa`.`cupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `vacaciones_recreativa`.`actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones_recreativa`.`actividades` ;

CREATE TABLE IF NOT EXISTS `vacaciones_recreativa`.`actividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NULL,
  `lugar` VARCHAR(80) NULL,
  `fechainicio` DATE NULL,
  `fechafin` DATE NULL,
  `horainicio` DATE NULL,
  `horafin` DATE NULL,
  `usuarios_id` INT NOT NULL,
  `articulos_id` INT NOT NULL,
  `cupos_id` INT NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividades_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_actividades_articulos1_idx` (`articulos_id` ASC),
  INDEX `fk_actividades_cupos1_idx` (`cupos_id` ASC),
  CONSTRAINT `fk_actividades_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `vacaciones_recreativa`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_articulos1`
    FOREIGN KEY (`articulos_id`)
    REFERENCES `vacaciones_recreativa`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_cupos1`
    FOREIGN KEY (`cupos_id`)
    REFERENCES `vacaciones_recreativa`.`cupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `vacaciones_recreativa`.`inscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacaciones_recreativa`.`inscripciones` ;

CREATE TABLE IF NOT EXISTS `vacaciones_recreativa`.`inscripciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `actividades_id` INT NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inscripciones_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_inscripciones_actividades1_idx` (`actividades_id` ASC),
  CONSTRAINT `fk_inscripciones_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `vacaciones_recreativa`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripciones_actividades1`
    FOREIGN KEY (`actividades_id`)
    REFERENCES `vacaciones_recreativa`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
